FROM rust:1.75-slim-bookworm AS builder

WORKDIR /app
COPY . .
RUN cargo build --release -p rento-api

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libpq5 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/rento-api .
COPY --from=builder /app/migrations ./migrations
EXPOSE 8000
CMD ["./rento-api"]
