[application]
name = "rento-admin"
asset_dir = "../../assets"

[web.app]
title = "Rento Admin"

[web.resource]
style = ["/tailwind.css"]

[web.watcher]
watch_path = ["../../assets", "src"]
reload_html = true

[web.resource.dev]
style = []