[package]
name = "rento-api"
version = "0.1.0"
edition = "2021"
default-run = "rento-api"


[[bin]]
name = "rento-api"
path = "src/main.rs"


[dependencies]
rento-core = { workspace = true }

# Web framework
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tower-sessions = { workspace = true }
tower-sessions-redis-store = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Database
sqlx = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Auth & Security
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }

# Validation
validator = { workspace = true }

# HTTP Client
reqwest = { workspace = true }

# Utilities
chrono = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Email
lettre = { workspace = true }

# OpenAPI / Docs
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

# Task Queue
apalis = { workspace = true }

# Encoding
base64 = "0.22"

# Config
config = { workspace = true }
dotenvy = { workspace = true }

# Image processing
image = { workspace = true }

# OAuth
openidconnect = { workspace = true }

rand = { workspace = true }