[application]
name = "rento-web"
asset_dir = "../../assets"

[web.app]
title = "RentoLink"

[web.resource]
style = ["/tailwind.css"]

[web.watcher]
watch_path = ["src"]
reload_html = true

[web.resource.dev]
style = []